version: '3.7'

services:
  server:
    build:
      context: ./server
      dockerfile: ./local.Dockerfile 
    image: rfsgea-server
    container_name: rfsgea-server
    command: npm run watch
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
      - PORT=4000
    networks:
      - rfsgea-network
    depends_on:
      - cache

  cache:
    image: redis:6.2-alpine
    container_name: rfsgea-cache
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
    networks:
      - rfsgea-network
      
  client:
    build:
      context: ./client
    image: rfsgea-client
    container_name: rfsgea-client
    command: npm run watch
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    # depends_on:
    #   - server
    ports:
      - "3000:3000"
    env_file: ./client/.env
    networks:
      - rfsgea-network

networks:
    rfsgea-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local
    cache:
      driver: local