version: '3.7'

services:
  ### Disabling server because it currently has no active endpoints

  # server:
  #   build:
  #     context: ./server
  #     dockerfile: ./local.Dockerfile 
  #   image: avocado-server
  #   container_name: avocado-server
  #   command: npm run watch
  #   volumes:
  #     - ./server:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - "4000:4000"
  #   env_file: ./server/.env
  #   environment:
  #     - NODE_ENV=development
  #   networks:
  #     - avocado-network
      
  client:
    build:
      context: ./client
    image: avocado-client
    container_name: avocado-client
    command: npm run watch
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    # depends_on:
    #   - server
    ports:
      - "3000:3000"
    env_file: ./client/.env
    networks:
      - avocado-network

networks:
    avocado-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local